# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='mid_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_adddress',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='office',
            name='tour_agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='yurjin_journal.TourAgency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourist',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='international_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя как в загранпаспорте'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='international_passport',
            field=models.CharField(blank=True, max_length=200, verbose_name='Загранпаспорт'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='international_passport_date_of_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия загранпаспорта'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='mid_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта РФ'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кем выдан паспорт РФ'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='passport_num',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер паспорта РФ'),
        ),
    ]
