# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_journal', '0002_auto_20170405_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='doc_get_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='excursion',
        ),
        migrations.AddField(
            model_name='contract',
            name='confirm_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='contract',
            name='doc_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи документов'),
        ),
        migrations.AddField(
            model_name='contract',
            name='excursions',
            field=models.TextField(blank=True, verbose_name='Включенные экскурсии'),
        ),
        migrations.AddField(
            model_name='contract',
            name='full_pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата полной оплаты'),
        ),
        migrations.AddField(
            model_name='contract',
            name='visa_risk_insurance',
            field=models.BooleanField(default=False, verbose_name='Включена страховка визового риска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status_full_name',
            field=models.CharField(max_length=200, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
