# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurjin_journal', '0003_auto_20170405_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='operator_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Сумма оператору'),
        ),
    ]
